# Generated by Django 3.0.5 on 2020-05-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeer', '0002_auto_20200507_2040'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeer',
            table='tbl_employeer',
        ),
    ]
