# Generated by Django 3.0.5 on 2020-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tbl_enquiries',
            },
        ),
        migrations.AddField(
            model_name='enquirytype',
            name='type_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
