# Generated by Django 3.0.5 on 2020-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_auto_20200503_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquirySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50)),
                ('source_color', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'mst_enquiry_sources',
            },
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
