# Generated by Django 3.0.5 on 2020-05-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_auto_20200503_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('enquirySource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiries.EnquirySource')),
                ('enquiryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquiries.EnquiryType')),
            ],
            options={
                'db_table': 'tbl_enquiries',
            },
        ),
    ]
