# Generated by Django 3.0.5 on 2020-05-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquirySource',
            new_name='enquiry_source',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiryType',
            new_name='enquiry_type',
        ),
    ]
