# Generated by Django 3.0.5 on 2020-05-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_auto_20200503_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Enquiries'},
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='status',
        ),
    ]
