# Generated by Django 3.0.5 on 2020-05-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customers',
        ),
    ]
